hellopy-dev:
  name: hellopy-dev
  namespace: hellopy
  project: devel-1234
  replicaCount: 7
  deploymentContainer:
    port: 5000
    command: ['./entrypoint.sh']
    livenessProbe:
      path: /
      failureThreshold: 3
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      path: /
      failureThreshold: 3
      initialDelaySeconds: 0
      periodSeconds: 10
      successTh...  batchSize: 10000
      region: eu-west-1
      retentionInDays: 10
    resourceTagging:
      enabled: true
      tags:
        Environment: demo
        Team: DevOps
  autoScaleUIGroups:
    replicas: 5
    role: worker
    settings:
      maxReplicas: 10
      minReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 75
    taskGroup:
      count: 3
      role: controller
      tags:
        NumberOfTasks: '5'
        UseSpotInstances: 'True'