payments-consumer:
  name: payments-consumer
  project: hackathon-2025-af24
  additionalLabels:
    env: development
    team: sre
  deploymentContainer:
    port: 5000
    livenessProbe:
      path: /api/health/liveness
      failureThreshold: 3
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      path: /api/health/readiness
      failureThreshold: 3
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      path: /api/health/liveness
      failureThreshold: 3
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  image:
    repository: us-central1-docker.pkg.dev/hackathon-2025-af24/davecolab/payments
    tag: latest
  resources:
    limits:
      cpu: 200m
      memory: 328Mi
    requests:
      cpu: 100m
      memory: 64Mi
  apm:
    enabled: true
  env:
    LOG_LEVEL: warning
